name: CD
run-name: Deploy to ${{ inputs.environment }} by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy"
        type: environment
        required: true

  workflow_call:
    inputs:
      environment:
        description: "The environment to deploy"
        type: string
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.lookup_environment_url.outputs.base_url}}
    concurrency: ${{ inputs.environment }}
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLY_CONFIG_PATH: ${{ secrets.FLY_CONFIG_PATH }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Look up environment url
        id: lookup_environment_url
        run: |
          echo "base_url=https://$(flyctl info --config $FLY_CONFIG_PATH -j | jq -r 'if .Hostname == "phoenixdiff-web-prod.fly.dev" then "phoenixdiff.org" else .Hostname end')" >> $GITHUB_OUTPUT
      - name: Deploy to fly
        run: flyctl deploy -c "$FLY_CONFIG_PATH" --remote-only
      - name: Notify Honeybadger
        uses: honeybadger-io/github-notify-deploy-action@v1
        with:
          api_key: ${{ secrets.HONEYBADGER_API_KEY }}
          environment: ${{ secrets.HONEYBADGER_ENV_NAME || inputs.environment }}
